### ISSUE TITLE
Default AvgPoolingOp only supports NHWC on device type CPU"

### ISSUE THREAD

**Issue by ghost** [cs-chan/ArtGAN#3]
But now I get 
"Default AvgPoolingOp only supports NHWC on device type CPU" while running CIFARGANAEsample.py 
![supports nhwc on device type cpu](https://user-images.githubusercontent.com/42616914/47128358-7ee6d680-d2ae-11e8-89c6-993f024d69fa.png)

and while trying to train CIFARGANAEtrick I get the following error 
![trick](https://user-images.githubusercontent.com/42616914/47128425-ba81a080-d2ae-11e8-8e6a-f697a5aa97f7.png)

is it due to environment used ?
I am using Ubuntu 16.04 LTS
Conda and Virtual Env. 
Python 2.7 
Latest versions of Neon and Aeon 
Tensorflow 1.10
CUDA 9.0
CuDnn 7.3.1 
what were the versions of Neon and Aeon for you ? 
Thanks in advance.

_Originally posted by @sunshinevirgo21 in https://github.com/cs-chan/ArtGAN/issue_comments#issuecomment-430857729_

**Comment by ghost** [comment]
Some thing I forgot to mention : I am running this on 1050ti.
I found out that CPU can only handle NHWC while the data used here is NCHW on GPU.
do you have any idea why i am getting a traceback to

2018-10-18 07:58:33.486367: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-10-18 07:58:33.624672: E tensorflow/core/common_runtime/executor.cc:697] Executor failed to create kernel. Invalid argument: Default AvgPoolingOp only supports NHWC on device type CPU
[[Node: Generator/AvgPool = AvgPoolT=DT_FLOAT, data_format="NCHW", ksize=[1, 1, 3, 3], padding="SAME", strides=[1, 1, 2, 2], _device="/job:localhost/replica:0/task:0/device:CPU:0"]]
Traceback (most recent call last):
File "CIFAR64GANAEsample.py", line 86, in
gen_img, gen_img128 = sess.run([samples, samples128])
File "/home/user/Downloads/venv/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 877, in run
run_metadata_ptr)
File "/home/user/Downloads/venv/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1100, in _run
feed_dict_tensor, options, run_metadata)
File "/home/user/Downloads/venv/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1272, in _do_run
run_metadata)
File "/home/user/Downloads/venv/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1291, in _do_call
raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Default AvgPoolingOp only supports NHWC on device type CPU
[[Node: Generator/AvgPool = AvgPoolT=DT_FLOAT, data_format="NCHW", ksize=[1, 1, 3, 3], padding="SAME", strides=[1, 1, 2, 2], _device="/job:localhost/replica:0/task:0/device:CPU:0"]]

**Comment by willtwr** [comment]
From the error messages, they seem to be related to how you installed your packages and environment settings as the codes are running with CPU.
Its difficult for us to debug them for you here.
Please google for the latest instructions on the installations and setups.

**Comment by ghost** [comment]
Okay thanks for replying. 
As suggested by you, if there is problem in packages and environment settings, Kindly tell me the proper environment to run the code as I am using the following : 
Ubuntu 16.04 LTS
Conda and Virtual Env.
Python 2.7
Latest versions of Neon and Aeon
Tensorflow 1.10
CUDA 9.0
CuDnn 7.3.1
MSI GL63 8RD (1050Ti/8GB)

Also please mention the settings for Pycharm environment you created. 
waiting for the reply...
